execution_env=local
#execution_env=remote

appURL=https://tutorialsninja.com/demo/
appURL2=http://localhost/opencart/upload/
#email=bhanuprasadb45@gmail.com
#password=Shiva@143
searchProductName=iPhone
email=Baaniveluri@gmail.com
password=Baani@143